"""Rebuild assets/logo-data.js from assets/logo.png.

The PDF needs the logo as base64. It cannot read it back off a canvas, because
browsers block that when the page is opened straight from disk. Run this after
replacing the logo. Needs Pillow.
"""
import base64
import io
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'assets', 'logo.png')
TARGET = os.path.join(ROOT, 'assets', 'logo-data.js')

SIZE = 160      # plenty for 44pt in the PDF and 56px on the page
COLOURS = 16    # the crest is nearly flat colour, so this stays small


def main():
    logo = Image.open(SOURCE).convert('RGBA').resize((SIZE, SIZE), Image.LANCZOS)

    # the PDF page is white, so flatten the transparency onto white
    flat = Image.new('RGB', logo.size, (255, 255, 255))
    flat.paste(logo, mask=logo.split()[3])

    buf = io.BytesIO()
    flat.quantize(colors=COLOURS).save(buf, format='PNG', optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode('ascii')

    with io.open(TARGET, 'w', encoding='utf-8', newline='\n') as out:
        out.write('// generated by tools/make-logo-data.py, do not edit\n')
        out.write("window.LOGO_PNG = 'data:image/png;base64," + b64 + "';\n")

    print('wrote %s (%d KB)' % (os.path.relpath(TARGET, ROOT), os.path.getsize(TARGET) // 1024))


if __name__ == '__main__':
    main()
