"""Rebuild assets/header-data.js from assets/header.png.

The PDF needs the banner as base64. It cannot read it back off a canvas, because
browsers block that when the page is opened straight from disk. Run this after
replacing the banner. Needs Pillow.
"""
import base64
import io
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'assets', 'header.png')
TARGET = os.path.join(ROOT, 'assets', 'header-data.js')

WIDTH = 900     # roughly 295 dpi at the size the PDF draws it
COLOURS = 16    # flat blue on white, so this stays small


def main():
    banner = Image.open(SOURCE).convert('RGBA')
    height = round(banner.height * WIDTH / banner.width)
    banner = banner.resize((WIDTH, height), Image.LANCZOS)

    # the PDF page is white, so flatten the transparency onto white
    flat = Image.new('RGB', banner.size, (255, 255, 255))
    flat.paste(banner, mask=banner.split()[3])

    buf = io.BytesIO()
    flat.quantize(colors=COLOURS).save(buf, format='PNG', optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode('ascii')

    with io.open(TARGET, 'w', encoding='utf-8', newline='\n') as out:
        out.write('// generated by tools/make-header-data.py, do not edit\n')
        out.write('window.HEADER_RATIO = %.4f;\n' % (banner.width / float(banner.height)))
        out.write("window.HEADER_PNG = 'data:image/png;base64," + b64 + "';\n")

    print('wrote %s (%d KB)' % (os.path.relpath(TARGET, ROOT), os.path.getsize(TARGET) // 1024))


if __name__ == '__main__':
    main()
